type: object
additionalProperties: true
required: ["localstorage_properties"]
properties:
  localstorage_properties:
    type: array
    items:
      type: object
      required: ["name", "description", "value_schema"]
      properties:
        name:
          type: string
        value_schema:
          type: object
        description:
          type: string
